### ISSUE TITLE
gbmm Function specification of random effects

### ISSUE THREAD

**Issue by jameswagner254** [rsparapa/bnptools#1]
I'm using v2.6 of the BART package. The vignette (2.6 or here) doesn't really provide an example of the use of the random effects feature. It's not completely clear how to incorporate the grouping variable. There is the u.train specification, but what if the same groups are available for the predictions? There is no "u.test". Should the grouping variable be part of x.test? Or does the function assume that the random effects are new "draws" from the same distribution? Thanks.

**Comment by rsparapa** [comment]
Hi James:

It is very much a work in progress.  Charley, one of the other developers, has a more advanced version, but we have not pushed it yet (more priors, allows multiple u's, intercepts and slopes, etc.).  So far, we have taken the position that the u's are not involved in the prediction since they have mean 0.  I think you will see some new code here in the next couple of months.

Rodney

**Comment by rsparapa** [comment]
Charley is in the process of adding his code now to bnptools/mxBART so stay tuned.  It might take him a couple of days.

**Comment by rsparapa** [comment]
The mxBART interface has roughly stabilized so now it is the preferred way to do BART mixed models.
