### ISSUE TITLE
Failed to install BART3

### ISSUE THREAD

**Issue by jlee52** [rsparapa/bnptools#2]
Hello,

I am trying to install BART3 and mxBART you developed, but I have trouble installing it.  It kept failing to compile. Do you have any idea to resolve this issue? I attached the error messages. 

** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG  -I'C:/Users/redea/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c BART3.cpp -o BART3.o
BART3.cpp:20:10: fatal error: BART3.h: No such file or directory
 #include <BART3.h>
          ^~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/i386/Makeconf:245: BART3.o] Error 1
ERROR: compilation failed for package 'BART3'

I look forward to hearing from you. Thank you,.

**Comment by rsparapa** [comment]
Yes, this appears to be a nasty R bug that I have only seen on Windows (Linux/macOS are fine).  Sorry, I don't know markdown (nor do I want to learn).  But here is the workaround in LaTeX.

\begin{frame}\frametitle{Installing BART R packages}

\begin{itemize}
\item There is NO bug in the BART3 package: it installs fine
on Linux and macOS, but not Windows 
\item The bug appears to be in R for Windows and I have
replicated the issue on a Windows laptop 
\item And I have a workaround
\item Although, this workaround is only needed on Windows,
it might be of interest to those on other platforms since
it provides some insight into how R builds/installs packages
\end{itemize}

\end{frame}

\begin{frame}\frametitle{Installing BART R packages}

\begin{itemize}
\item Where does R install packages?
\item This is dictated by the {\tt .libPaths} function\\
issue the following to see which directory/directories\\
$>$ {\tt .libPaths() } 
\item On all platforms, there can be permissions issues
\item The last directory listed
is the global directory and you will typically not have
permission to install R packages there
\item The first directory is the default location\\
so if there is only one directory can run into permission issues
\item So you can create your own directory
\item R recognizes the following location as your HOME
directory
\item {\tt /home/USERNAME} on macOS/Linux (or {\tt $~$} for short) \\
{\tt c:$\backslash$Users$\backslash$USERNAME} on Windows
 (there is no shortcut)
\item Let's create the {\tt Rlib} directory in HOME on Windows\\
{\tt cd c:$\backslash$Users$\backslash$USERNAME}\\
{\tt c:}\\
{\tt mkdir Rlib} \\
{\tt cd} and {\tt mkdir} are roughly the same command on all platforms
\end{itemize}

\end{frame}

\begin{frame}\frametitle{Installing BART R packages}

\begin{itemize}
\item Now create a file namede {\tt .Rprofile} in HOME
with one of the following lines so that the {\tt Rlib} is the
default location to install R packages\\
{\tt .libPaths("$~$/Rlib") \#\# macOS/Linux syntax}\\
{\tt .libPaths("c:/Users/USERNAME/Rlib") \#\# Windows}
\item I also like to specify the default CRAN mirror in this file
by the most complete and reliable mirror that I have found\\
add the following line\\
{\tt options(repos=c(CRAN="http://lib.stat.cmu.edu/R/CRAN"))}
\item Now when you start a new R session these settings should
be operational: to check type\\
$>$ {\tt .libPaths() }
\item If that is ok, then install the dependencies for the BART
packages from CRAN
\end{itemize}
$>$ {\tt install.packages("RcppEigen", dependencies=TRUE)}\\
$>$ {\tt install.packages("abind", dependencies=TRUE)}
\end{frame}

\begin{frame}\frametitle{Installing BART R packages}
\begin{itemize}
\item Download {\tt bnptools-master.zip} from 
\url{https://github.com/rsparapa/bnptools}
\item Extract the archive into some directory: it will contain the 
{\tt BART3}, {\tt mxBART} and {\tt hbart} sub-directories
\item Build the BART3 package\\
{\tt R CMD build --no-build-vignettes BART3}
\item I typically build without the vignettes that take a long
time
\item And install it:
{\tt R CMD INSTALL BART3\_4.3.tar.gz}
%\item You should see preprocessor statements like 
\end{itemize}
You should see preprocessor statements like 
{\tt -I../inst/include/}
\begin{itemize}
\item %If you see these, then everything should work
Since the BART3 R package has {\tt Makevars} files\\
for macOS/Linux, {\tt BART3/src/Makevars.in}\\ and Windows, 
{\tt BART3$\backslash$src$\backslash$Makevars.win}
\item In the {\tt src} directory, they each contain the line\\
{\tt PKG\_CPPFLAGS = -I../inst/include/}
\item Now build/install the mxBART package, i.e.,\\
{\tt R CMD build --no-build-vignettes mxBART}\\
{\tt R CMD INSTALL mxBART\_1.1.tar.gz}
\end{itemize}
\end{frame}

\begin{frame}\frametitle{Installing BART R packages}

\begin{itemize}
\item If you didn't see that compiler statement it is a bug
\item This R bug appears to be only a Windows issue since
everything seems to work fine on macOS/Linux
\item So I'm assuming Windows for the rest of this slide
\item To workaround create the following directory\\
{\tt mkdir C:$\backslash$Users$\backslash$USERNAME$\backslash$Rlib$\backslash$BART$\backslash$include }
\item And copy the header files there\\
{\tt xcopy /s BART3$\backslash$include 
Rlib$\backslash$BART$\backslash$include}
\item Now edit the file {\tt BART3$\backslash$DESCRIPTION}
\item Change line number 30 from ``{\tt LinkingTo: Rcpp}''
\item To ``{\tt LinkingTo: Rcpp, BART}''
\item Then re-build/re-install it\\
{\tt R CMD build --no-build-vignettes BART3}\\
{\tt R CMD INSTALL BART3\_4.3.tar.gz}
\end{itemize}

\end{frame}

**Comment by jlee52** [comment]
Hi Rodney,

Yeah, I am using Windows, so it makes this trouble. I will try this
workaround to resolve my issues. Appreciate it.
By the way, may I ask one more question if you don't mind? I have a concern
about BART with random effects.

Let me explain what I am handling. I am conducting research with
post-stroke gait data. Because it is a nested dataset, I was looking for a
sort of mixed-model-based approach. I noticed that bart is a superior
tree-based algorithm, so I tested several bart packages including
bartMachine, BART, and dbarts for a variable selection. Additionally, I
tested rbart from dbarts taking random effects into account. Based on my
dataset, all of the packages I tested gave me similar results. All
high-ranked variables are consistent but slightly different in low-ranked
variables.

These testing results draw me a question whether I should use a mixed
model-based Bart. Based on my testing, I am not convinced that random
effects affect a lot on the variable selection using bart. Would you give
me some advice regarding bart with random effect? I was wondering if
currently available bart packages without considering random effects are
good enough to investigate the nested dataset.

I appreciate your help on my issue. Happy New Year.

Best regards,
Jeonghwan Jay Lee
Ph.D. student, Department of Mechanical Engineering
The University of Texas at Austin | +1 512-771-4956
jlee.page; Rewire Lab <http://sites.utexas.edu/rewire/>; Texas Robotics
<http://robotics.utexas.edu/>;

204 E Dean Keeton St, ETC 4.134
Austin, TX 78712

**Comment by rsparapa** [comment]
I would try the mxBART package for random effects too.  It is certainly possible that the variable selection could change based on the mixed model.

**Comment by jlee52** [comment]
Thank you for your response. It makes sense to me. I will definitely try
the mxBART package.

One last question. Is rbart (
https://www.rdocumentation.org/packages/dbarts/versions/0.9-20/topics/rbart)
in the dbarts package a way different from you mxBART? rbart function in
dbarts is also for a bart modeling with random effects. I want to make sure
that it would be similar except for additional functionality such as a
sparse Dirichlet prior.

Best
Jeonghwan Jay Lee
Ph.D. student, Department of Mechanical Engineering
The University of Texas at Austin | +1 512-771-4956
jlee.page; Rewire Lab <http://sites.utexas.edu/rewire/>; Texas Robotics
<http://robotics.utexas.edu/>;

204 E Dean Keeton St, ETC 4.134
Austin, TX 78712

**Comment by rsparapa** [comment]
Yes, all of my stuff is here https://github.com/rsparapa/bnptools so checkout mxBART which I worked on with my student Charley (install BART3 first and mxBART should just install fine: if not, then use the workaround).  I have not been involved with other groups such as Vincent Dorie's dbarts.  Not saying anything negative: it is just a fact.  And it has been quite a while since I've looked at other packages.  Due to copyright/etc., I don't look at other's source code unless I am filing a bug report or something.

**Comment by jlee52** [comment]
Understood. Thank you for the clarification on it!
I hope you had a great day and stay healthy!

Best
Jeonghwan Jay Lee
Ph.D. student, Department of Mechanical Engineering
The University of Texas at Austin | +1 512-771-4956
jlee.page; Rewire Lab <http://sites.utexas.edu/rewire/>; Texas Robotics
<http://robotics.utexas.edu/>;

204 E Dean Keeton St, ETC 4.134
Austin, TX 78712

**Comment by jlee52** [comment]
Hi Rodney,

I successfully installed BART3 and mxBART packages. I sincerely appreciate
your quick response.

Just for your information, I noticed that your suggested workaround didn't
work for my environment. However, I figured out an alternative. For
instance, just copying the file of "Makevars.win" to /src folder in
BART3_4.3.tar.gz resolved all issues. With this, I don't need to add a new
library path and edit DESCRIPTION. As you described windows OS has an issue
with admin access. Build can't properly generate "Makevars.win" in tar.gz.
By adding this file, the installment works well.

Best regards,
Jeonghwan Jay Lee
Ph.D. student, Department of Mechanical Engineering
The University of Texas at Austin | +1 512-771-4956
jlee.page; Rewire Lab <http://sites.utexas.edu/rewire/>; Texas Robotics
<http://robotics.utexas.edu/>;

204 E Dean Keeton St, ETC 4.134
Austin, TX 78712
